"""Add cover_photo column to Club table

Revision ID: 02b1e0f9941a
Revises: 
Create Date: 2025-01-11 19:20:13.998420

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '02b1e0f9941a'
down_revision = None
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.add_column(sa.Column('cover_photo', sa.String(length=200), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('club', schema=None) as batch_op:
        batch_op.drop_column('cover_photo')

    # ### end Alembic commands ###
