"""Updated database models

Revision ID: dfbe59c50fe6
Revises: 85107ca97d6a
Create Date: 2025-01-16 17:34:48.777057

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = 'dfbe59c50fe6'
down_revision = '85107ca97d6a'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.create_unique_constraint('unique_event_participation', ['event_id', 'student_id'])

    with op.batch_alter_table('join_request', schema=None) as batch_op:
        batch_op.add_column(sa.Column('created_at', sa.DateTime(), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('join_request', schema=None) as batch_op:
        batch_op.drop_column('created_at')

    with op.batch_alter_table('event_participant', schema=None) as batch_op:
        batch_op.drop_constraint('unique_event_participation', type_='unique')

    # ### end Alembic commands ###
